import streamlit as st
from AI.ai_helper import ask_gemini


def generate_problem(topic, difficulty, language):

    prompt = f"""
You are a coding interview trainer for college students.

Generate ONE coding practice problem.

Topic: {topic}
Difficulty: {difficulty}
Programming Language: {language}

Return the response in this format:

Problem:
<problem statement>

Input:
<input description>

Output:
<output description>

Example:
<input example>
<output example>

Constraints:
<constraints>

Do NOT provide the solution or code.
"""


    return ask_gemini(prompt)


def get_solution(problem, language):

    prompt = f"""
You are an expert programming instructor.

Solve the following coding problem in {language}.

Problem:
{problem}

Provide:

1. Explanation
2. Approach
3. Time Complexity
4. Space Complexity
5. Complete working code

Make the solution beginner-friendly.
"""

    return ask_gemini(prompt)


def show_coding():

    st.title("💻 AI Coding Practice")

    st.write(
        "Practice coding problems generated by AI based on your "
        "preferred topic, difficulty and programming language."
    )

    st.divider()

    col1, col2 = st.columns(2)

    with col1:

        topic = st.selectbox(
            "Topic",
            [
                "Arrays",
                "Strings",
                "Searching",
                "Sorting",
                "Linked Lists",
                "Stacks",
                "Queues",
                "Hashing",
                "Recursion",
                "Trees",
                "Graphs",
                "Dynamic Programming"
            ]
        )

        difficulty = st.selectbox(
            "Difficulty",
            [
                "Easy",
                "Medium",
                "Hard"
            ]
        )

    with col2:

        language = st.selectbox(
            "Programming Language",
            [
                "Python",
                "Java",
                "C++",
                "C"
            ]
        )

    st.divider()

    if st.button(
        " Generate Coding Problem",
        use_container_width=True
    ):

        with st.spinner(
            " AI is generating your coding problem..."
        ):

            try:

                problem = generate_problem(
                    topic,
                    difficulty,
                    language
                )

                st.session_state.coding_problem = problem
                st.session_state.coding_solution = None

            except Exception as e:

                st.error(
                    f"❌ Could not generate problem: {str(e)}"
                )

    if st.session_state.get("coding_problem"):

        st.divider()

        st.subheader(" Coding Problem")

        st.write(
            st.session_state.coding_problem
        )

        st.divider()

        st.subheader(" Your Solution")

        user_code = st.text_area(
            "Write your code here:",
            height=250,
            placeholder="Write your solution..."
        )

        if st.button(
            " Show AI Solution",
            use_container_width=True
        ):

            with st.spinner(
                " AI is preparing the solution..."
            ):

                try:

                    solution = get_solution(
                        st.session_state.coding_problem,
                        language
                    )

                    st.session_state.coding_solution = solution

                except Exception as e:

                    st.error(
                        f"❌ Could not generate solution: {str(e)}"
                    )

    if st.session_state.get("coding_solution"):

        st.divider()

        st.subheader("✅ AI Solution")

        st.write(
            st.session_state.coding_solution
        )

    st.divider()

    if st.button(
        "⬅ Back to Student Features",
        use_container_width=True
    ):

        st.session_state.page = "student_features"
        st.rerun()